spring:
  datasource:
    url: jdbc:postgresql://192.168.178.69:5432/budgetdb
    username: budget
    password: budget
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://codefuchs.dev/auth/realms/money-bunny
          jwk-set-uri: https://codefuchs.dev/auth/realms/money-bunny/protocol/openid-connect/certs

cors:
  allowed-origins:
    - http://tinyhome:3100
    - http://100.119.149.50:3100
    - http://tinyhome.foxhound-shark.ts.net:3100
    - http://codefuchs.dev


