spring:
  datasource:
    url: jdbc:postgresql://192.168.178.69:5432/budgetdb
    username: budget
    password: budget
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.178.69:8180/auth/realms/money-bunny
          jwk-set-uri: http://192.168.178.69:8180/auth/realms/money-bunny/protocol/openid-connect/certs

cors:
  allowed-origins:
    - https://codefuchs.dev


