spring:
  application:
    name: household-budget-backend
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/master
          jwk-set-uri: http://localhost:8180/realms/master/protocol/openid-connect/certs
cors:
  allowed-origins:
    - http://localhost
    - http://127.0.0.1

springdoc:
  swagger-ui:
#    path: /swagger-ui/index.html
#    config-url: /api/swagger-ui/swagger-config
    url: /api/v3/api-docs