spring:
  datasource:
    url: jdbc:postgresql://192.168.178.69:5432/budgetdb
    username: budget
    password: budget
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.codefuchs.dev/realms/money-bunny
          jwk-set-uri: https://auth.codefuchs.dev/realms/money-bunny/protocol/openid-connect/certs

cors:
  allowed-origins:
    - https://codefuchs.dev
    - https://api.codefuchs.dev
    - https://auth.codefuchs.dev
    - https://*.codefuchs.dev


