spring:
  application:
    name: household-budget-backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
cors:
  allowed-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
