name: Build and Deploy Spring Boot App
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Flyway Migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql:/postgresql:5432/budgetdb
          user: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:src/main/resources/database/migrations

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."192.168.178.69:5000"]
              http = true
              insecure = true
              
      - name: Configure Docker for insecure registry
        run: |
          mkdir -p ~/.docker
          echo '{"insecure-registries":["192.168.178.69:5000"]}' > ~/.docker/config.json
          
      - name: Login to Self-Hosted Registry
        uses: docker/login-action@v2
        with:
          registry: http://192.168.178.69:5000
          username: tinyhome
          password: bunni
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 192.168.178.69:5000/spring-boot-app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          insecure: true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=192.168.178.69:5000/spring-boot-app:buildcache
          cache-to: type=registry,ref=192.168.178.69:5000/spring-boot-app:buildcache,mode=max
